# Generated by Django 2.2 on 2019-04-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250)),
                ('title', models.TextField(blank=True, null=True)),
                ('href', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_error', models.BooleanField()),
                ('is_file_downloaded', models.BooleanField()),
                ('doc_html', models.TextField(blank=True, null=True)),
                ('doc_txt', models.TextField(blank=True, null=True)),
                ('is_document_downloaded', models.BooleanField()),
                ('is_files_downloaded', models.BooleanField()),
            ],
            options={
                'db_table': 'main_documents',
                'managed': False,
            },
        ),
    ]
