# Generated by Django 2.2 on 2019-04-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=250)),
                ('name_kz', models.CharField(max_length=250)),
                ('name_translit', models.CharField(max_length=250)),
                ('birth', models.DateField()),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
