# Generated by Django 2.2 on 2019-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190422_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name_kz',
            new_name='first_name_kz',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name_ru',
            new_name='first_name_lat',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name_translit',
            new_name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth',
        ),
        migrations.AddField(
            model_name='person',
            name='last_name_kz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name_lat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='raw_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surename_kz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surename_lat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surename_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
