# Generated by Django 2.2 on 2019-05-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190504_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='surename_ru',
            new_name='surname_ru',
        ),
    ]
