# Generated by Django 2.2 on 2019-05-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190506_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='surename_kz',
            new_name='surname_kz',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='surename_lat',
            new_name='surname_lat',
        ),
    ]
