# Generated by Django 2.2 on 2019-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190506_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name_ru',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name_ru',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='surname_ru',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
