# Generated by Django 2.2 on 2019-05-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_person_search_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindocuments',
            options={},
        ),
    ]
