# Generated by Django 2.2 on 2019-05-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_maindocuments_search_f'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindocuments',
            old_name='search_f',
            new_name='search_field',
        ),
    ]
