# Generated by Django 2.2 on 2019-05-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190507_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'verbose_name': 'Суд', 'verbose_name_plural': 'Суды'},
        ),
        migrations.AlterModelOptions(
            name='maindocuments',
            options={'verbose_name': 'Судебное решение', 'verbose_name_plural': 'Судебные решения'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Физ. лицо', 'verbose_name_plural': 'Физ. лица'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должностя'},
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=250)),
                ('name_kz', models.CharField(max_length=250)),
                ('bin', models.CharField(max_length=12)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.City')),
                ('faunders', models.ManyToManyField(blank=True, null=True, to='app.Person')),
            ],
            options={
                'verbose_name_plural': 'Компании',
                'verbose_name': 'Компания',
            },
        ),
    ]
