# Generated by Django 2.2 on 2019-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190508_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='faunders_text',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sity_text',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
